
# LoadBalancer due to testing. Enables the pod to be accessible outside the cluster

apiVersion: v1
kind: Service
metadata:
  name: jobservice
spec:
  clusterIP: 10.96.0.12
  selector:
    app: jobservice
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.0.2.127

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobservice-deployment
  labels:
    app: jobservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobservice
  template:
    metadata:
      labels:
        app: jobservice
    spec:
      containers:
      - name: jobservice
        image: jobservice
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080



---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: job_service_db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: psltest
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume  # Sets PV's name
  labels:
    type: local  # Sets PV's type to local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 50Mi # Sets PV Volume
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim  # Sets name of PVC
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany  # Sets read and write access
  resources:
    requests:
      storage: 50Mi  # Sets volume size
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres  # Sets Deployment name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:10.1 # Sets Image
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432  # Exposes container port
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgres # Sets service name
  labels:
    app: postgres # Labels and Selectors
spec:
  clusterIP: 10.96.0.11
  ports:
    - port: 5432 # Sets port to run the postgres application
  selector:
    app: postgres