
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - protocol: "TCP"
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: eu.gcr.io/${PROJECT_ID}/auth_service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: auth-database-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-database-config
  labels:
    app: auth-database
data:
  POSTGRES_DB: userdb
  POSTGRES_USER: ${AUTH_DB_USER}
  POSTGRES_PASSWORD: ${AUTH_DB_PASS}
  AUTH_PRIVATE_KEY: ${AUTH_PRIVATE_KEY}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: default-storage-class
provisioner: kubernetes.io/gce-pd
volumeBindingMode: Immediate
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  type: pd-standard
  fstype: ext4
  replication-type: none
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-database-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: standard-rwo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-database  # Sets Deployment name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-database
  template:
    metadata:
      labels:
        app: auth-database
    spec:
      containers:
        - name: auth-database
          image: postgres:10.1 # Sets Image
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432  # Exposes container port
          envFrom:
            - configMapRef:
                name: auth-database-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: auth-database-vol
              subPath: postgres
      volumes:
        - name: auth-database-vol
          persistentVolumeClaim:
            claimName: auth-database-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: auth-database # Sets service name
  labels:
    app: auth-database # Labels and Selectors
spec:
  ports:
    - port: 5432 # Sets port to run the postgres application
  selector:
    app: auth-database