apiVersion: batch/v1
kind: Job
metadata:
  name: solver-instance
spec:
  completions: 1
  template:
    metadata:
      name: solver-instance
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl"]
        args: ["-Mbignum=bpi", "-wle", "print bpi(2000)"]
      # Do not restart containers after they exit
      restartPolicy: Never
  # of retries before marking as failed.
  backoffLimit: 4