#Holds the database secrets
apiVersion: v1
kind: ConfigMap
metadata:
  name: fs-postgres-config
  labels:
    app: fs-postgres
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: psltest
  _POSTGRES_HOST: fs-postgres.default.svc.cluster.local:5432
  _HOST: 0.0.0.0:9090
  _STORAGE_DIR: /mnt/hdd/dumbaf
