#Holds the database secrets
apiVersion: v1
kind: ConfigMap
metadata:
  name: fs-postgres-config
  labels:
    app: fs-postgres
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: psltest
  _POSTGRES_HOST: fs-postgres.default.svc.cluster.local:5432
  _HOST: 0.0.0.0:9090
  _STORAGE_DIR: /mnt/hdd/dumbaf
---
#The data storage (and access)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fs-postgres-pv-volume
provisioner: pd.csi.storage.gke.io
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: pd-balanced
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fs-postgres-pv-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: fs-postgres-pv-volume
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fs-postgres  # Sets Deployment name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fs-postgres
  template:
    metadata:
      labels:
        app: fs-postgres
    spec:
      hostname: fsservice
      containers:
        - name: postgres
          image: postgres:latest # Sets Image
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432  # Exposes container port
          envFrom:
            - configMapRef:
                name: fs-postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              subPath: dumbaf #Fix some bug
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: fs-postgres-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: fs-postgres
  labels:
    app: fs-postgres
spec:
  type: ClusterIP
  ports:
   - port: 5432
  selector:
   app: fs-postgres