apiVersion: apps/v1
kind: Deployment
metadata:
  name: fs-postgres  # Sets Deployment name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fs-postgres
  template:
    metadata:
      labels:
        app: fs-postgres
    spec:
      hostname: fsservice
      containers:
        - name: postgres
          image: postgres:latest # Sets Image
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432  # Exposes container port
          envFrom:
            - configMapRef:
                name: fs-postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              subPath: dumbaf #Fix some bug
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: fs-postgres-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: fs-postgres
  labels:
    app: fs-postgres
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
   app: fs-postgres