apiVersion: apps/v1
kind: Deployment
metadata:
  name: fs-service  # Sets Deployment name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fs-service
  template:
    metadata:
      labels:
        app: fs-service
    spec:
      containers:
        - name: fs-service
          image: eu.gcr.io/solveit-369711/fs_service:latest # Sets Image
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 9090  # Exposes container port
          envFrom:
            - configMapRef:
                name: fs-postgres-config
          volumeMounts:
            - mountPath: /mnt/hdd
              subPath: dumbaf #Fix some bug
              name: fsservicevol
      volumes:
        - name: fsservicevol
          persistentVolumeClaim:
            claimName: fs-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: fs-service # Sets service name
  labels:
    app: fs-service # Labels and Selectors
spec:
  type: NodePort # Sets service type
  ports:
    - port: 9090 # Sets port to run the postgres application
  selector:
    app: fs-service
