name: Dastardly Security Scan
run-name: ${{ github.actor }} is running a security scan 🚀
on: 
  workflow_dispatch:
  
jobs:
  Make-Scan:
    runs-on: ubuntu-latest
    steps:
      - name: Run Dastardly Action Step
        uses: PortSwigger/dastardly-github-action@main
        with:
          target-url: 'http://34.90.15.75/'
